name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          sudo chown -R $(whoami):$(whoami) $GITHUB_WORKSPACE || true
          sudo chmod -R u+rwx $GITHUB_WORKSPACE || true
          sudo rm -rf $GITHUB_WORKSPACE/* $GITHUB_WORKSPACE/.* || true
        continue-on-error: true

      - name: Checkout depot
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
          echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
          echo "DB_NAME=${{secrets.DB_NAME}}" >> .env
          echo "DB_USER=${{secrets.DB_USER}}" >> .env
          echo "DB_PASSWORD=${{secrets.DB_PASS}}" >> .env
          echo "REDIS_HOST=${{secrets.REDIS_HOST}}" >> .env
          echo "REDIS_PORT=${{secrets.REDIS_PORT}}" >> .env
          echo "REDIS_DB=${{secrets.REDIS_DB}}" >> .env

      - name: DÃ©marrer le conteneur
        run: |
          docker network inspect labo03-network >/dev/null 2>&1 || docker network create labo03-network
          docker compose build
          docker compose up -d

      - name: Attendre MySQL
        run: |
          sleep 10
          timeout=60
          until docker exec mysql mysqladmin ping -h localhost -u root -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then
              echo "MySQL failed to start"
              exit 1
            fi
          done
          sleep 5

      - name: Run tests
        working-directory: src
        run: docker exec -u 1004:1004 store_manager  pytest || true
      
      - name: Cleanup
        if: failure()
        run: docker compose down -v

      - name: Check containers
        if: success()
        run: docker ps